AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for EMR - Spark flow in Cadabra 
  
Parameters:  
  InstanceType:
    Type: String
    Default: m5.xlarge
  ReleaseLable:
    Type: String 
    Default: emr-5.21.0

Resources:
  emrRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CadabraEMRrole
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: elasticmapreduce.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole'
  emrEc2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role'
  emrEc2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref emrEc2Role

  emrCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Applications:
        - Name: Spark
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: !Ref InstanceType
          Market: ON_DEMAND
          Name: cadabraEMRmaster
        CoreInstanceGroup:
          InstanceCount: 2
          InstanceType: !Ref InstanceType
          Market: ON_DEMAND
          Name: cadabraEMRcore
      Name: CadabraEmrCluster
      JobFlowRole: !Ref emrEc2InstanceProfile
      ServiceRole: !Ref emrRole
      ReleaseLabel: !Ref ReleaseLable
      VisibleToAllUsers: true