AWSTemplateFormatVersion: 2010-09-09
Description: "S3 bucket nested template"

Parameters: 
  BucketName:
    Type: String
    Default: orderlogs-rama1
    Description: Provide Unique bucket name 

Resources: 
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Ref BucketName
Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
    Description: Name of the simple Amazon S3 bucket